import Head from "next/head";
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Secured Graphical Authentication for web Applications</title>
        <meta
          name="Ahmed Final Year Project"
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Ellipse 460.png" />
      </Head>
      <main className="app__flex homepage">
        <article className="column-flex modal">
          <h1 className="head-text" style={{ marginBottom: "12px" }}>
            Welcome to HomeTech
          </h1>
          <p className="p-text-2" style={{ marginBottom: "55px" }}>
            We protect your credentials from any form of shoulder surfing
            attacks
          </p>
          <div className="modal-btn column-flex" style={{marginBottom: '150px'}}>
            <button onClick={() => router.push('/register')} className="primary-btn">Register</button>
            <button onClick={() => router.push('/login')} className="secondary-btn">Sign in</button>
          </div>
          <div className="modal-footer app__flex-2">
            <p>Privacy and Policy</p>
            <p>FAQ</p>
          </div>
        </article>
      </main>
    </>
  );
}
